AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloudformation to forward SES email to another address


Parameters:
  ApplicationName:
    Type: String
    Description: The name of the application to deploy
  EnvironmentName:
    Type: String
    Description: The name of the environment to deploy
  FromAddress:
    Type: String
    Description: Email forwarded from address
  ToAddress:
    Type: String
    Description: Email forwarded to address


Resources:
  ReceiptRule:
    Type: AWS::SES::ReceiptRule
    Properties:
      RuleSetName: default
      Rule:
        Name: !Sub ${ApplicationName}-${EnvironmentName}-rule
        Enabled: true
        ScanEnabled: true
        Actions:
          - S3Action:
              BucketName: !Ref EmailBucket
              ObjectKeyPrefix: ''
          - SNSAction:
              Encoding: UTF-8
              TopicArn: !Ref EmailForwarderTopic

  EmailForwarderTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ApplicationName}-${EnvironmentName}-receipt-topic
      Subscription:
        - Endpoint: !GetAtt EmailForwarderFunction.Arn
          Protocol: lambda

  EmailForwarderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-${EnvironmentName}-receipt-function
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs16.x
      Timeout: 30
      Environment:
        Variables:
          FROM_ADDRESS: !Ref FromAddress
          TO_ADDRESS: !Ref ToAddress
      Events:
        SNSEmail:
          Type: SNS
          Properties:
            Topic: !Ref EmailForwarderTopic
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
  EmailForwarderLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${EmailForwarderFunction}

  EmailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ApplicationName}-${EnvironmentName}-email-storage
      VersioningConfiguration:
        Status: Enabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  EmailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EmailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSESPuts
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${EmailBucket}/*
            Condition:
              StringEquals:
                aws:Referer: !Ref AWS::AccountId
