version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - make package
artifacts:
  files:
    - template.packaged.yml
